version: 2

models:
  - name: daily_region_summary

    data_tests:
      - unique:
          arguments:
            column_name: "concat(cast(Date as string), '-', Region)"

    columns:
      - name: Date
        data_tests:
          - not_null

      - name: Region
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Île-de-France', 'Hauts-de-France']