GCP_PROJECT_ID = "energy-data-platform-505816"
BQ_DATASET_ID = "energy"
BQ_CLEAN_TABLE_ID = "clean_energy"
BQ_STAGING_TABLE_ID = "staging_energy"
BQ_DAILY_SUMMARY_TABLE_ID = "daily_region_summary"

BQ_STAGING_TABLE_FULL_ID = (
    f"{GCP_PROJECT_ID}.{BQ_DATASET_ID}.{BQ_STAGING_TABLE_ID}"
)

BQ_CLEAN_TABLE_FULL_ID = (
    f"{GCP_PROJECT_ID}.{BQ_DATASET_ID}.{BQ_CLEAN_TABLE_ID}"
)

BQ_DAILY_SUMMARY_TABLE_FULL_ID = (
    f"{GCP_PROJECT_ID}.{BQ_DATASET_ID}.{BQ_DAILY_SUMMARY_TABLE_ID}"
)